import numpy as np
import time
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def large_scale_cracking_model():
    """
    Kinetic model for an Olefin Steam Cracker simulating a large-scale
    reaction network with over 40,000 kinetic reactions.

    Since a real mechanism with 40,000+ reactions (like those generated by RMG
    or detailed CHEMKIN mechanisms) requires external database files, this script
    procedurally generates a highly complex mock reaction network to demonstrate
    the computational approach for solving such a large system.
    """

    print("Initializing large-scale kinetic model...")

    # Define scale of the system
    num_species = 500  # Number of distinct chemical species
    num_reactions = 40000  # Number of kinetic reactions

    print(f"Species: {num_species}")
    print(f"Reactions: {num_reactions}")

    # Constants
    R = 8.314 # Gas constant, J/(mol K)
    T_C = 800 # Temperature in Celsius
    T_K = T_C + 273.15 # Temperature in Kelvin

    # -------------------------------------------------------------------------
    # 1. Procedural Generation of the Reaction Network
    # -------------------------------------------------------------------------
    print("Generating reaction network and rate constants...")

    # Random seed for reproducibility
    np.random.seed(42)

    # Generate Arrhenius parameters for 40,000 reactions
    # Pre-exponential factor A (s^-1)
    A = np.random.uniform(1e10, 1e15, num_reactions)
    # Activation energy Ea (J/mol)
    Ea = np.random.uniform(50000, 300000, num_reactions)

    # Calculate rate constants k for all reactions at the given temperature
    k = A * np.exp(-Ea / (R * T_K))

    # Define stoichiometry
    # For simplicity in this mock mechanism, we assume unimolecular decomposition
    # or isomerization: A -> B + C (or A -> B)
    #
    # reactant_indices: [num_reactions] - index of the reactant species
    # product_indices: [num_reactions, 2] - indices of product species (second can be -1 if unimolecular)

    reactant_indices = np.random.randint(0, num_species, num_reactions)
    product_indices = np.zeros((num_reactions, 2), dtype=int)

    for i in range(num_reactions):
        # Pick 1 or 2 products
        num_prods = np.random.choice([1, 2])
        p1 = np.random.randint(0, num_species)
        while p1 == reactant_indices[i]: # Avoid A -> A
            p1 = np.random.randint(0, num_species)

        if num_prods == 1:
            product_indices[i] = [p1, -1]
        else:
            p2 = np.random.randint(0, num_species)
            product_indices[i] = [p1, p2]

    # Designate specific indices for tracked major species
    # e.g., 0: Ethane, 1: Ethylene, 2: Hydrogen
    ETHANE_IDX = 0
    ETHYLENE_IDX = 1
    HYDROGEN_IDX = 2

    # Manually ensure the primary reaction (Ethane -> Ethylene + H2) exists and is dominant
    reactant_indices[0] = ETHANE_IDX
    product_indices[0] = [ETHYLENE_IDX, HYDROGEN_IDX]
    k[0] = 3.0e14 * np.exp(-280000 / (R * T_K)) # Actual ethane cracking rate

    # -------------------------------------------------------------------------
    # 2. ODE System Definition
    # -------------------------------------------------------------------------
    print("Defining ODE system for massive species network...")

    # We use a highly vectorized ODE function for performance.
    # Solving 500 coupled ODEs driven by 40,000 reaction rates requires vectorization.
    def model(y, t):
        # y is an array of concentrations for all 500 species

        # Calculate rates for all 40,000 reactions
        # rate = k * [Reactant]
        rates = k * y[reactant_indices]

        # Initialize derivatives array
        dYdt = np.zeros(num_species)

        # Fast accumulation of derivatives
        # Subtract consumption from reactants
        np.add.at(dYdt, reactant_indices, -rates)

        # Add production to products
        # Product 1
        np.add.at(dYdt, product_indices[:, 0], rates)

        # Product 2 (where applicable, indicated by index != -1)
        valid_p2_mask = product_indices[:, 1] != -1
        p2_indices = product_indices[:, 1][valid_p2_mask]
        p2_rates = rates[valid_p2_mask]
        np.add.at(dYdt, p2_indices, p2_rates)

        return dYdt

    # -------------------------------------------------------------------------
    # 3. Execution
    # -------------------------------------------------------------------------

    # Initial conditions: Pure ethane feed
    y0 = np.zeros(num_species)
    y0[ETHANE_IDX] = 1.0

    # Time points (residence time: 0 to 1 second)
    t = np.linspace(0, 1.0, 100)

    print(f"Solving ODEs for {num_species} species and {num_reactions} reactions...")
    start_time = time.time()

    # Solve ODEs
    # Note: For very stiff massive systems, Radau or BDF methods (via solve_ivp)
    # are better, but odeint works well enough for this demonstration.
    solution = odeint(model, y0, t)

    end_time = time.time()
    print(f"Simulation completed in {end_time - start_time:.2f} seconds.")

    # Extract major species
    C_ethane_t = solution[:, ETHANE_IDX]
    C_ethylene_t = solution[:, ETHYLENE_IDX]
    C_hydrogen_t = solution[:, HYDROGEN_IDX]

    # Calculate conversion and yield
    conversion = (y0[ETHANE_IDX] - C_ethane_t) / y0[ETHANE_IDX] * 100
    yield_ethylene = C_ethylene_t / y0[ETHANE_IDX] * 100

    # Plot results
    print("Generating plots...")
    plt.figure(figsize=(12, 8))

    plt.subplot(2, 1, 1)
    plt.plot(t, C_ethane_t, label='Ethane (C2H6)', color='blue', linewidth=2)
    plt.plot(t, C_ethylene_t, label='Ethylene (C2H4)', color='green', linewidth=2)
    plt.plot(t, C_hydrogen_t, label='Hydrogen (H2)', color='red', linewidth=2)

    # Plot a few random minor species
    for i in range(3, 8):
        plt.plot(t, solution[:, i], linestyle=':', alpha=0.6, label=f'Byproduct {i}')

    plt.xlabel('Residence Time (s)')
    plt.ylabel('Normalized Concentration')
    plt.title(f'Steam Cracking Profile ({num_reactions:,} Reactions Network)')
    plt.legend()
    plt.grid(True)

    plt.subplot(2, 1, 2)
    plt.plot(t, conversion, label='Ethane Conversion (%)', color='blue', linestyle='--')
    plt.plot(t, yield_ethylene, label='Ethylene Yield (%)', color='green', linestyle='--')
    plt.xlabel('Residence Time (s)')
    plt.ylabel('Percentage (%)')
    plt.title('Main Product Conversion and Yield')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.savefig('large_scale_cracker_results.png')
    print("Done. Results saved to 'large_scale_cracker_results.png'")

if __name__ == '__main__':
    large_scale_cracking_model()
